(function() {var implementors = {};
implementors["tokio_proto"] = ["impl&lt;T&gt; <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"tokio_proto/streaming/pipeline/advanced/struct.Pipeline.html\" title=\"struct tokio_proto::streaming::pipeline::advanced::Pipeline\">Pipeline</a>&lt;T&gt; <span class=\"where fmt-newline\">where T: <a class=\"trait\" href=\"tokio_proto/streaming/pipeline/advanced/trait.Dispatch.html\" title=\"trait tokio_proto::streaming::pipeline::advanced::Dispatch\">Dispatch</a></span>","impl&lt;T&gt; <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"tokio_proto/streaming/multiplex/advanced/struct.Multiplex.html\" title=\"struct tokio_proto::streaming::multiplex::advanced::Multiplex\">Multiplex</a>&lt;T&gt; <span class=\"where fmt-newline\">where T: <a class=\"trait\" href=\"tokio_proto/streaming/multiplex/advanced/trait.Dispatch.html\" title=\"trait tokio_proto::streaming::multiplex::advanced::Dispatch\">Dispatch</a></span>","impl&lt;T, E&gt; <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"tokio_proto/util/client_proxy/struct.Response.html\" title=\"struct tokio_proto::util::client_proxy::Response\">Response</a>&lt;T, E&gt; <span class=\"where fmt-newline\">where E: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">Error</a>&gt;</span>","impl&lt;Kind, P&gt; <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"tokio_proto/struct.Connect.html\" title=\"struct tokio_proto::Connect\">Connect</a>&lt;Kind, P&gt; <span class=\"where fmt-newline\">where P: <a class=\"trait\" href=\"tokio_proto/trait.BindClient.html\" title=\"trait tokio_proto::BindClient\">BindClient</a>&lt;Kind, <a class=\"struct\" href=\"https://docs.rs/tokio-core/0.1/tokio_core/net/tcp/struct.TcpStream.html\" title=\"struct tokio_core::net::tcp::TcpStream\">TcpStream</a>&gt;</span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
